#!/bin/bash

sh sh_scripts_single/cirrhosis_cae_cluster.sh 2 1 &&
sh sh_scripts_single/cirrhosis_cae_cluster.sh 2 2 &&
sh sh_scripts_single/cirrhosis_dae_cluster.sh 2 1 &&
sh sh_scripts_single/cirrhosis_dae_cluster.sh 2 2 &&
sh sh_scripts_single/cirrhosis_sae_cluster.sh 2 1 &&
sh sh_scripts_single/cirrhosis_sae_cluster.sh 2 2 &&
sh sh_scripts_single/cirrhosis_vae_cluster.sh 2 1 &&
sh sh_scripts_single/cirrhosis_vae_cluster.sh 2 2 &&
sh sh_scripts_single/colorectal_cae_cluster.sh 2 1 &&
sh sh_scripts_single/colorectal_cae_cluster.sh 2 2 &&
sh sh_scripts_single/colorectal_dae_cluster.sh 2 1 &&
sh sh_scripts_single/colorectal_dae_cluster.sh 2 2 &&
sh sh_scripts_single/colorectal_sae_cluster.sh 2 1 &&
sh sh_scripts_single/colorectal_sae_cluster.sh 2 2 &&
sh sh_scripts_single/colorectal_vae_cluster.sh 2 1 &&
sh sh_scripts_single/colorectal_vae_cluster.sh 2 2 &&
sh sh_scripts_single/ibd_cae_cluster.sh 2 1 &&
sh sh_scripts_single/ibd_cae_cluster.sh 2 2 &&
sh sh_scripts_single/ibd_dae_cluster.sh 2 1 &&
sh sh_scripts_single/ibd_dae_cluster.sh 2 2 &&
sh sh_scripts_single/ibd_sae_cluster.sh 2 1 &&
sh sh_scripts_single/ibd_sae_cluster.sh 2 2 &&
sh sh_scripts_single/ibd_vae_cluster.sh 2 1 &&
sh sh_scripts_single/ibd_vae_cluster.sh 2 2 &&
sh sh_scripts_single/obesity_cae_cluster.sh 2 1 &&
sh sh_scripts_single/obesity_cae_cluster.sh 2 2 &&
sh sh_scripts_single/obesity_dae_cluster.sh 2 1 &&
sh sh_scripts_single/obesity_dae_cluster.sh 2 2 &&
sh sh_scripts_single/obesity_sae_cluster.sh 2 1 &&
sh sh_scripts_single/obesity_sae_cluster.sh 2 2 &&
sh sh_scripts_single/obesity_vae_cluster.sh 2 1 &&
sh sh_scripts_single/obesity_vae_cluster.sh 2 2 &&
sh sh_scripts_single/t2d_cae_cluster.sh 2 1 &&
sh sh_scripts_single/t2d_cae_cluster.sh 2 2 &&
sh sh_scripts_single/t2d_dae_cluster.sh 2 1 &&
sh sh_scripts_single/t2d_dae_cluster.sh 2 2 &&
sh sh_scripts_single/t2d_sae_cluster.sh 2 1 &&
sh sh_scripts_single/t2d_sae_cluster.sh 2 2 &&
sh sh_scripts_single/t2d_vae_cluster.sh 2 1 &&
sh sh_scripts_single/t2d_vae_cluster.sh 2 2 &&
sh sh_scripts_single/wt2d_cae_cluster.sh 2 1 &&
sh sh_scripts_single/wt2d_cae_cluster.sh 2 2 &&
sh sh_scripts_single/wt2d_dae_cluster.sh 2 1 &&
sh sh_scripts_single/wt2d_dae_cluster.sh 2 2 &&
sh sh_scripts_single/wt2d_sae_cluster.sh 2 1 &&
sh sh_scripts_single/wt2d_sae_cluster.sh 2 2 &&
sh sh_scripts_single/wt2d_vae_cluster.sh 2 1 &&
sh sh_scripts_single/wt2d_vae_cluster.sh 2 2
